server:
  port: 8084

spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: HOTELSERVICE
            uri: lb://HOTELSERVICE
            predicates:
              - Path=/hotels/**,/staffs/**
          - id: RATINGSERVICE
            uri: lb://RATINGSERVICE
            predicates:
              - Path=/rating/**
          - id: USERSERVICE
            uri: lb://USERSERVICE
            predicates:
              - Path=/users/**
    discovery:
      enabled: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka

