server:
  port: 8081

spring:
  application:
      name: UserService
  config:
    import: configserver:http://localhost:8085
  datasource:
    url: jdbc:mysql://localhost:3306/hotelms
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

